feat: add Open-Graph integration
prepas-mp2i/prepas-mp2i.fr pull request #74
Opened 2024-07-23 20:33 UTC by Truiteseche

Hi 👋
Fix a spelling mistake d98196fa43e79582e61c7f3be113c77fa0ea309f
Fix a bug that prevented the website from being served a6fedb5d374256e211010eeb32f1569d89f16b98
Add Open-Graph  integrations (embedded links in social medias) 6a264db97b1e402c9f0201abf9c5e3e8c385ce2c

2024-07-24 06:42 UTC, ajayat commented
For me, everything is fine 👌
Good to see OG integrations.

2024-07-24 08:16 UTC, Triw-12 requested changes
Bonnes idées !
Cependant, pour les balises d'Open-graph, c'est une bonne amélioration mais ces balises seront identiques peu importe la page, or il serait souhaitable de garder l'unicité des pages, et que les pages gardent leurs types (articles pour la plupart), leur titre, leur description, et leur url... 
Ces modifications sont cependant tout à fait acceptable si elle s'applique uniquement à la page principale

2024-07-24 21:06 UTC, Triw-12 commented
Après quelques recherches, il y a bien une intégration d'OG mais il n'est pas forcément configuré : https://gohugo.io/templates/embedded/#configure-open-graph
(La fonction {{ template "_internal/opengraph.html" . }} apparait bien dans les entêtes de Loveit)

2024-07-24 23:43 UTC, Truiteseche commented
Merci pour vos retours, je check ça demain 👍

2024-07-28 15:32 UTC, Triw-12 requested changes

2024-07-28 15:32 UTC, Triw-12 commented on layouts/partials/head/meta.html
> +<meta property="og:image" content="{{ .Site.Params.home.profile.avatarURL}}">
```suggestion
<meta property="og:image" content="https://prepas-mp2i.fr{{ .Site.Params.home.profile.avatarURL}}">
```
Les url relatives ne marchent pas : https://stackoverflow.com/questions/70049918/fb-opengraph-ogimage-link-a-folder

2024-07-28 16:34 UTC, Truiteseche commented
Bien vu @Triw-12

2024-07-28 17:31 UTC, Triw-12 approved these changes
C'est ok pour moi !

2024-07-28 17:31 UTC, merged